name = "Conor McShane"
email = "conor.d.mcshane@outlook.com"
work_email = "conor.mcshane@yahooinc.com"

[hosts]
  [hosts.gpg]

  work  = "117E2CFC450E2BDF60D6E6F19F9C252869DE2E5F"
  torii = "563D8518C3DF748018C8F0E07A914829A62D6DEA"

  [hosts.desktop]
    hostname = "honshu"
    monitor_240hz = "DP-2"
    monitor_144hz = "DP-0"

    [hosts.desktop.ssh]
    public = "~/.ssh/keys/public/honshu"
    private = "~/.ssh/keys/private/honshu"

  [hosts.server]
    hostname = "hokkaido"

    [hosts.server.ssh]
    public = "~/.ssh/keys/public/server"
    private = "~/.ssh/keys/private/server"

  [hosts.macbook]
    hostname = "PY60HY3QW3"

    [hosts.macbook.ssh]
      [hosts.macbook.ssh.personal]
      public = "~/.ssh/keys/public/macbook"
      private = "~/.ssh/keys/private/macbook"

      [hosts.macbook.ssh.work]
      public = "~/.ssh/keys/public/work"
      private = "~/.ssh/keys/private/work"

  [hosts.wsl]
    [hosts.wsl.ssh]
    public = "~/.ssh/keys/public/chiba"
    private = "~/.ssh/keys/private/chiba"
