name = "Conor McShane"
email = "conor.d.mcshane@outlook.com"
work_email = "conor.mcshane@yahooinc.com"
copyright_year = 2024

# 2023-12-16 04:07
# Will change to new eventually...
# new method is using keepassxc database instead of age and the hacky way of decrypting
file_encryption_method = "new"

[hosts]
  [hosts.gpg]

  [hosts.desktop]
    hostname = "nara"
    monitor_240hz = "DP-2"
    monitor_144hz = "DP-0"
    gpg_id = "563D8518C3DF748018C8F0E07A914829A62D6DEA"

    [hosts.desktop.ssh]
    public = "~/.ssh/keys/nara/nara.pub"
    private = "~/.ssh/keys/nara/nara"

  [hosts.server]
    hostname = "hokkaido"

    [hosts.server.ssh]
    public = "~/.ssh/keys/hokkaido/hokkaido.pub"
    private = "~/.ssh/keys/hokkaido/hokkaido"

  [hosts.macbook]
    hostname = "PY60HY3QW3"
    gpg_id = "117E2CFC450E2BDF60D6E6F19F9C252869DE2E5F"

    [hosts.macbook.ssh]
      [hosts.macbook.ssh.personal]
      public = "~/.ssh/keys/macbook/macbook.pub"
      private = "~/.ssh/keys/macbook/macbook"

      [hosts.macbook.ssh.work]
      public = "~/.ssh/keys/work/work.pub"
      private = "~/.ssh/keys/work/work"
