name = "Conor McShane"
email = "conor.d.mcshane@gmail.com"
work_email = "conor.mcshane@yahooinc.com"

[hosts]
  [hosts.gpg]
  unified = "F86191F6CF88CCE1D908775633A923AB357604B2"
  work = "117E2CFC450E2BDF60D6E6F19F9C252869DE2E5F"

  [hosts.desktop]
    [hosts.desktop.ssh]
    public = "~/.ssh/keys/public/desktop-yubikey"
    private = "~/.ssh/keys/private/desktop-yubikey"

  [hosts.server]
    [hosts.server.ssh]
    public = "~/.ssh/keys/public/server"
    private = "~/.ssh/keys/private/server"

  [hosts.macbook]
    [hosts.macbook.ssh]
      [hosts.macbook.ssh.personal]
      public = "~/.ssh/keys/public/macbook"
      private = "~/.ssh/keys/private/macbook"

      [hosts.macbook.ssh.work]
      public = "~/.ssh/keys/public/macbook-work"
      private = "~/.ssh/keys/private/macbook-work"
