NAME = "Conor McShane"
EMAIL = "conor.d.mcshane@gmail.com"

[gpg]
	MACBOOK = "C59E2EA148098193BEEEE42087BFE2E84FE74F61"
	SERVER = "7032F7F9BC73C52B99956EB1F79E4AE90F072A31"
	DESKTOP = "26521FB9AEA047007F6D49489B8AC2D618B9D0E1"

[ssh]
	MACBOOK = "~/.ssh/server"
	SERVER = "~/.ssh/server"
	DESKTOP = "~/.ssh/desktop"
