name = "Conor McShane"
email = "conor.d.mcshane@gmail.com"

[hosts]

[hosts.desktop]
gpg = "26521FB9AEA047007F6D49489B8AC2D618B9D0E1"
  [hosts.desktop.ssh]
  public = "~/.ssh/keys/desktop-yubikey-public.pub"
  private = "~/.ssh/desktop-yubikey"

[hosts.server]
gpg = "7032F7F9BC73C52B99956EB1F79E4AE90F072A31"
  [hosts.server.ssh]
  public = "~/.ssh/keys/server-public"
  private = "~/.ssh/server"

[hosts.macbook]
gpg = "C59E2EA148098193BEEEE42087BFE2E84FE74F61"
  [hosts.macbook.ssh]
  public = "~/.ssh/keys/macbook-public"
  private = "~/.ssh/macbook"
