#!/usr/bin/env bash
#
# bspwmrc
#
# Copyright (C) 2020 dindybutts <lewdavatar at gmail dot com>
#
# Distributed under terms of the GPLv3 license.

bspc config pointer_motion_interval 40

bspc config top_padding 0
bspc config bottom_padding 0
bspc config window_gap 6
bspc config border_width 2
bspc config click_to_focus true
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config active_border_color   "#ebdbb2"
bspc config focused_border_color  "#ebdbb2"
bspc config presel_feedback_color "#ebdbb2"

bspc monitor DP-4 -n 0 -d I II III IV V
bspc monitor DP-0 -n 1 -d VI VII VIII IX
bspc monitor HDMI-0 -n 1 -d Tablet

bspc rule -a 'Blender' desktop='^4'
bspc rule -a 'Thunderbird' desktop='^5'
bspc rule -a 'Gimp' desktop='^5'
bspc rule -a 'Discord' desktop='^8'
bspc rule -a 'firefox' desktop='^9'
bspc rule -a 'krita' desktop='^10'
bspc rule -a 'OpenToonz' desktop='^10'

bspc rule -a Firefox: Dialog state=floating
bspc rule -a 'Zathura' state=tiled
bspc rule -a 'krita' state=fullscreen
bspc rule -a 'helvum' state=fullscreen
bspc rule -a 'OpenToonz' state=fullscreen
