version: '3.8'

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "caddy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${DOCKER_DIR}/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "${DOCKER_DIR}/caddy/data:/data"
      - "${DOCKER_DIR}/caddy/config:/config"
    depends_on:
      - "authelia"
      - "miniserve"
    restart: unless-stopped
    environment:
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - PORT_AUTHELIA=${PORT_AUTHELIA}
      - PORT_MINISERVE=${PORT_MINISERVE}
      - PORT_QBITTORRENT=${PORT_QBITTORRENT}
      - PORT_GITEA=${PORT_GITEA}
      - PORT_MINECRAFT=${PORT_MINECRAFT}
      - PORT_SSH=${PORT_SSH}
      - TZ="Europe/Dublin"
    networks:
      - cool

  miniserve:
    container_name: "miniserve"
    image: "svenstaro/miniserve"
    volumes:
      - "${DOCKER_DIR}/miniserve/files:/tmp"
    environment:
      - TZ="Europe/Dublin"
    command: "--readme -i=0.0.0.0 --auth=user:${PASSWORD_MINISERVE} /tmp"
    restart: unless-stopped
    networks:
      - cool

  authelia:
    container_name: "authelia"
    image: "authelia/authelia"
    volumes:
      - "${DOCKER_DIR}/authelia/configuration:/config"
      - "${DOCKER_DIR}/authelia/users_database:/data"
    ports:
      - "${PORT_AUTHELIA}:8080"
    environment:
      - TZ="Europe/Dublin"
    restart: unless-stopped
    networks:
      - cool

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  cool:
