version: '3.8'

services:
  caddy:
    container_name: "caddy"
    image: "caddy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${DOCKER_DIR}/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "${DOCKER_DIR}/caddy/data:/data"
      - "${DOCKER_DIR}/caddy/config:/config"
    depends_on:
      - "authelia"
      - "miniserve"
      - "qbittorrent"
      - "crowdsec"
    restart: unless-stopped
    environment:
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - PORT_AUTHELIA=${PORT_AUTHELIA}
      - PORT_MINISERVE=${PORT_MINISERVE}
      - PORT_QBITTORRENT=${PORT_QBITTORRENT}
      - PORT_GITEA=${PORT_GITEA}
      - PORT_MINECRAFT=${PORT_MINECRAFT}
      - PORT_SSH=${PORT_SSH}
      - TZ="Europe/Dublin"

  authelia:
    container_name: "authelia"
    image: "authelia/authelia"
    volumes:
      - "${DOCKER_DIR}/authelia/configuration:/config"
      - "${DOCKER_DIR}/authelia/users_database:/data"
    ports:
      - "${PORT_AUTHELIA}:8080"
    environment:
      - TZ="Europe/Dublin"
    restart: unless-stopped

  crowdsec:
    container_name: "crowdsec"
    image: "crowdsecurity/crowdsec"
    ports:
      - "6060:6060"
      - "6061:6061"
    volumes:
      - "${DOCKER_DIR}/crowdsec/data:/var/lib/crowdsec/data"
      - "${DOCKER_DIR}/crowdsec/config:/etc/crowdsec"
      - "${DOCKER_DIR}/crowdsec/logs:/var/log/crowdsec"
      - "/var/run/docker.sock:/var/run/docker.sock" # add this line
    environment:
      - CROWDSEC_MODE=online
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
      - TZ="Europe/Dublin"
    restart: unless-stopped

  miniserve:
    container_name: "miniserve"
    image: "svenstaro/miniserve"
    ports:
      - "${PORT_MINISERVE}:8080"
    volumes:
      - "${DOCKER_DIR}/miniserve/files:/tmp"
    environment:
      - TZ="Europe/Dublin"
    command: "--readme -i=0.0.0.0 --auth=user:${PASSWORD} /tmp"
    restart: unless-stopped

  qbittorrent:
    container_name: "qbittorrent"
    image: "dyonr/qbittorrentvpn"
    volumes:
      - "${DOCKER_DIR}/qbittorrent/config:/config"
      - "/mnt/downloads:/downloads"
    ports:
      - "${PORT_QBITTORRENT}:8080"
    environment:
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
      - LAN_NETWORK=192.168.0.0/24
      - TZ="Europe/Dublin"
    cap_add:
      - "NET_ADMIN"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
