version: '3.8'

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "caddy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${DOCKER_DIR}/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "${DOCKER_DIR}/caddy/data:/data"
      - "${DOCKER_DIR}/caddy/config:/config"
    depends_on:
      - "miniserve"
    restart: unless-stopped
    environment:
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - PORT_AUTHELIA=${PORT_AUTHELIA}
      - PORT_MINISERVE=${PORT_MINISERVE}
      - PORT_QBITTORRENT=${PORT_QBITTORRENT}
      - PORT_GITEA=${PORT_GITEA}
      - PORT_MINECRAFT=${PORT_MINECRAFT}
      - PORT_SSH=${PORT_SSH}
      - TZ="Europe/Dublin"
    networks:
      - cool

  miniserve:
    container_name: "miniserve"
    image: "svenstaro/miniserve"
    volumes:
      - "${DOCKER_DIR}/miniserve/files:/tmp"
    environment:
      - TZ="Europe/Dublin"
    command: "--readme -i=0.0.0.0 --auth=user:${PASSWORD_MINISERVE} /tmp"
    restart: unless-stopped
    networks:
      - cool

networks:
  cool:
