# install-packages-mac.sh
#
# Copyright (C) 2024 Conor McShane
#
# Distributed under terms of the GPLv3 license.
#

# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# brew-packages.txt was generated by running `brew leaves -r > brew-packages.txt` NOT `brew list > brew-packages.txt` as the latter includes dependencies
xargs brew install < ./brew-packages.txt
