# ; vim: set ft=toml:

encryption = "age"
[age]
	identity = "~/key.txt"
	recipient = "age17ta4xdx32z5zu3a8u8xh4yxkenenczdcwdp8uwmdwtvv6mt8ufpsnure6h"

[keepassxc]
	database = "~/onedrive/Passwords.kdbx"
