live_config_reload = true

[bell]
animation = "EaseOutExpo"

[colors.bright]
black = "0x928374"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe3a84e"

[colors.normal]
black = "0x665c54"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe78a4e"

[colors.primary]
background = "0x32302f"
foreground = "0xebdbb2"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "tewi"
style = "Regular"

[font.bold_italic]
family = "tewi"
style = "Regular"

[font.italic]
family = "tewi"
style = "Regular"

[font.normal]
family = "tewi"
style = "Regular"

[scrolling]
history = 1000
multiplier = 3

[window.padding]
x = 5
y = 5
